### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by max-franklin**
@RulerOf ,

I saw you created this branch for updating the role to template the logging config out. 

I updated the template to leverage yaml dumping, as that is essentially what it was doing before too, but with more required fields to get the job done. 

It looks like you were needing some molecule tests, and I added those as well. 

What would you think of merging this into your branch to update your PR here: https://github.com/newrelic/infrastructure-agent-ansible/pull/168

Also, I refreshed this branch with the latest changes from the main branch.

### CODE REVIEW

**Comment by RulerOf** [comment]
@max-franklin how lovely, I'd be happy to! I had to develop this for a specific project and haven't done any Ansible work since, so the playbook I wrote is just running on my fork 😅

You caught me on my way to bed, but I'll review this tomorrow (or possibly Sunday) and bring it into my PR. Thanks a ton!

**Comment by max-franklin** [comment]
Sounds great! Also, my approach is slightly different from that of the original (i.e., no more source_type and source_value fields). Basically, it mirrors the config setup documented here: https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/#configure

Which in turn makes me think that the readme will need to be updated too, if the maintainers are OK with this change.

Hope you have a nice night!

**Comment by max-franklin** [comment]
Performed a rebase so I could verify my commits. Sorry for missing this the first time!

**Review by RulerOf — COMMENTED** [review]
@max-franklin the code looks good to me, but I wanted to run the test. I try to run molecule and get to the point where I quit last time.

```
╰─❯ molecule --version
molecule 4.0.2 using python 3.10
    ansible:2.13.5
    delegated:4.0.2 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```

Trying to run molecule gives me this:
```
╰─❯ molecule test --all --parallel
CRITICAL Failed to validate /Users/andrewbobulsky/Projects/officedepot/infrastructure-agent-ansible/molecule/configure/molecule.yml

["Additional properties are not allowed ('lint' was unexpected)"]
```

If I remove the excess `lint` keys from the provisioner/verifier config, I still end up with [this problem](https://github.com/ansible-community/molecule/issues/3336), even when I set a `role_name` and `namespace`:

```
╰─❯ molecule test --all --parallel
<snip>
ERROR    Computed fully qualified role name of newrelic.newrelic-infra does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.
```

How are you even able to run the test suite?

**Comment by max-franklin** [comment]
Hey @RulerOf ,

I ran into the role-name issue as well. To get around it, I had to add the following ansible lint config:

```bash
(.ansible.venv) maxwellfranklin@Maxwells-MacBook-Pro infrastructure-agent-ansible % cat ~/.ansible-lint 
---
skip_list:
  - role-name
(.ansible.venv) maxwellfranklin@Maxwells-MacBook-Pro infrastructure-agent-ansible % 
```

One other thing, it looks like this project wasn't setup in a way that permits running `molecule test --all`.

If you check out the code for `molecule/configure/create.yml` and `molecule/targz/create.yml`, you'll see they depend on the docker containers being up and running already:

```yml
---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
  - debug:
      msg: This is a no-op. Please ensure you have run create on the default scenario.
```

The end result is that I can run `molecule test` for the default scenario, and that works fine (only sharing verify recap below to eliminate copious output):

```bash
PLAY RECAP *********************************************************************
centos-7                   : ok=12   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
centos-8                   : ok=12   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
oraclelinux-8              : ok=12   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
ubuntu-1804                : ok=12   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
ubuntu-2004                : ok=12   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

INFO     Verifier completed successfully.
INFO     Running default > cleanup
WARNING  Skipping, cleanup playbook not configured.
INFO     Running default > destroy
```

But if I want to test everything, it'll generate an error, since the `configure` and `targz` scenarios don't actually generate instances as part of their test suite.

I can try and update this PR to make it such that the `configure` and `targz` scenarios work with `test --all`, but I'm almost wondering if it should be addressed in a separate issue. What do you think? 

P.S. - 

Edited to include my molecule version details:

```bash
(.ansible.venv) maxwellfranklin@Maxwells-MacBook-Pro infrastructure-agent-ansible % molecule --version
molecule 3.6.0 using python 3.8 
    ansible:2.13.5
    delegated:3.6.0 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
(.ansible.venv) maxwellfranklin@Maxwells-MacBook-Pro infrastructure-agent-ansible % 
```

**Comment by max-franklin** [comment]
One other thing worth mentioning. While `molecule test --all` does not work since the `configure` and `targz` scenarios don't create their instances, you can still manually run a test sequence like so:

```bash
# create default scenario
molecule create

# converge default scenario, setting up our instances
molecule converge

# converge configure scenario (depends on pre-existing instances)
molecule converge -s configure

# verify configure scenario (depends on pre-existing instances)
molecule verify -s configure

# clean up
molecule destroy
```

**Comment by max-franklin** [comment]
@RulerOf , have you had a chance to try testing?

**Comment by RulerOf** [comment]
@max-franklin I ran into yet another issue and haven't had the chance to pick this back up, likely won't until Friday afternoon.

**Comment by max-franklin** [comment]
Gotcha, sounds good!

**Comment by RulerOf** [comment]
@max-franklin I haven't gotten to troubleshoot this further but I the error I still end up with

**Comment by max-franklin** [comment]
@RulerOf , what are you executing and what is the error?

I noticed that if I switch to using molecule 4.0.2 which appears to be what you're using, I receive the following error when attempting to create resources for the default scenario:

```bash
% molecule --version
molecule 4.0.2 using python 3.8 
    ansible:2.13.5
    delegated:4.0.2 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
% molecule create
CRITICAL Failed to validate /Users/maxwellfranklin/infrastructure-agent-ansible/molecule/default/molecule.yml

["Additional properties are not allowed ('lint' was unexpected)"]
```

Can you try downgrading to v3.6.0:

```bash
% python3 -m pip install molecule==3.6.0
```

Then seeing if `molecule create` works?

**Comment by RulerOf** [comment]
@max-franklin That appears to have been the problem. Is there a way to pin molecule versions inside of the project? ([lol](https://github.com/newrelic/infrastructure-agent-ansible/pull/145/files)).

edit: running tests now on my end.

**Comment by max-franklin** [comment]
Doh! Glad it's working now :) Looking forward to hearing how the testing goes.

**Comment by RulerOf** [comment]
@max-franklin Wow... this test suite is awful. I appreciate you taking the time to write tests that fit into it though, and that all seem to work :)

**Comment by RulerOf** [comment]
Thanks! I'll push this along into my PR now. Apologies for the delay, had to do everything I did on this outside of normal work hours lol.

**Comment by max-franklin** [comment]
I have to agree... I think the project could use some more TLC...! 
No worries about the delay. I am in the same boat!

**Comment by max-franklin** [comment]
And thanks for all the time you put into this!

**Pull request merged**
